### ISSUE TITLE
Adding common functions to the shell framework

### ISSUE THREAD

**Issue by kofan** [flant/shell-operator#104]
Shell operator [`v1.0.0-beta.7`](https://github.com/flant/shell-operator/releases/tag/v1.0.0-beta.7) has introduced a [framework](https://github.com/flant/shell-operator/tree/master/frameworks/shell) to facilitate the creation of shell hooks.
To make it even greater I'd suggest include to the framework some of the common functions that you use throughout the examples, for instance: **[common/functions.sh](https://github.com/flant/shell-operator/blob/master/examples/104-secret-copier/hooks/common/functions.sh)**.
Thank you!

**Comment by distol** [comment]
Thank you much for pointing out. @driusha, can you work on it?

1. I think it would be even better to update all the examples to use the mentioned framework. It already has an order of magnitude better implementation of the `run` function, at least.
2. Speaking about the function [`kubectl::replace_or_create`](https://github.com/flant/shell-operator/blob/master/examples/104-secret-copier/hooks/common/functions.sh#L9-L17) – not sure about that. I consider it too hacky and too clumsy to include in the framework. In some nearest future (probably this or next week), we are going to introduce the ability, for hooks, to return to the shell-operator list of "tasks." The tasks would be smth like "create an object with the following definition" or "patch the object foo in ns bar using the following jq expression," and so on.

**Comment by shurup** [comment]
We now have [shell_lib.sh](https://github.com/flant/shell-operator/blob/master/https://github.com/flant/shell-operator/blob/master/). It was also introduced during our [KubeCon talk on shell-operator](https://medium.com/flant-com/meet-the-shell-operator-kubecon-36c14ba2f8fe).
