### ISSUE TITLE
Update kubectl in the Docker images

### ISSUE THREAD

**Issue by brandonkal** [flant/shell-operator#141]
kubectl is now four major versions behind. Please update it to the latest stable version. I'd love to start experimenting with this.

Also, tagging and releasing the first stage of [this build](https://hub.docker.com/r/flant/shell-operator/dockerfile) would make it easier for others to choose the kubectl version they want.

**Comment by diafour** [comment]
Hello @brandonkal!

>  Please update it to the latest stable version.

I've updated `kubectl` to v1.17.4 and added alpine-3.11 build in PR #146.


> Also, tagging and releasing the first stage of this build would make it easier for others to choose the kubectl version they want.

Can you be more specific, what kind of image that will be? A scratch image with shell-operator binary or something else?

One can replace `kubectl` binary in image with just one RUN command:

```
FROM flant/shell-operator:latest
RUN wget https://storage.googleapis.com/kubernetes-release/release/v1.17.4/bin/linux/amd64/kubectl -O /bin/kubectl && \
    chmod +x /bin/kubectl
ADD hooks /hooks
```

I replace `shell-operator` binary for testing purposes in that manner. Is it a suitable solution for your task?

**Comment by brandonkal** [comment]
Thank you for the update. Regarding my second request, now that I think about it, it wouldn't make much sense to publish the go build container with the shell-operator binary.

A scratch container with the binary would probably be more interesting (as an alternative to curl/wget) simply as a means to fetch only the built binary. But that is not really necessary now as the size of flant/shell-operator image is already pretty slim.
