### ISSUE TITLE
Error: executeHookOnEvent is a forbidden property

### ISSUE THREAD

**Issue by Demon-DK** [flant/shell-operator#155]
#### Environment
    Host OS: CentOS 8
    Kubernetes Version: 1.17.4
    Cluster Environment: (bare-metal)
    Image version: flant/shell-operator:v1.0.0-beta.8

#### Precondition
 Just trying to use the default example of a namespace monitoring
 [https://github.com/flant/shell-operator/tree/master/examples/102-monitor-namespaces](https://github.com/flant/shell-operator/tree/master/examples/102-monitor-namespaces)

#### Issue
* Pod is not starting and going to 'CrashLoopBackOff' state
* Main issue is "... kubernetes.executeHookOnEvent is a forbidden property ..."
> Couldn't figure out why the property is forbidden

#### Related checks and logs
```
$ kubectl rbac-lookup shell-operator -k serviceaccount
SUBJECT           SCOPE          ROLE
shell-operator    cluster-wide   ClusterRole/view

$ kubectl describe clusterrole view | grep namespace
  Resources           URLs  Resource Names  Verbs
  ---------           ----  --------------  ----- 
  namespaces/status    []        []      [get list watch]
  namespaces           []        []      [get list watch]
```

```
{
  "level": "info",
  "msg": "Kubernetes client is configured successfully with 'out-of-cluster' config",
  "operator.component": "KubernetesAPIClient",
  "time": "2020-03-25T14:52:28+02:00"
}
{
  "level": "info",
  "msg": "Initialize hooks manager. Search for and load all hooks.",
  "time": "2020-03-25T14:52:28+02:00"
}
{
  "hook": "namespace-monitor.sh",
  "level": "info",
  "msg": "Load config from '/hooks/namespace-monitor.sh'",
  "phase": "config",
  "time": "2020-03-25T14:52:28+02:00"
}
{
  "level": "error",
  "msg": "MAIN Fatal: initialize hook manager: creating hook 'namespace-monitor.sh': load hook 'namespace-monitor.sh' config: 1 error occurred:\n\t* kubernetes.executeHookOnEvent is a forbidden property\n\n\nhook --config output: configVersion: v1\nkubernetes:\n- name: OnCreateDeleteNamespace\n  apiVersion: v1\n  kind: Namespace\n  executeHookOnEvent:\n  - Added\n  - Deleted\n- name: OnModifiedNamespace\n  apiVersion: v1\n  kind: Namespace\n  executeHookOnEvent:\n  - Modified\n  jqFilter: \".metadata.labels\"\n\n",
  "time": "2020-03-25T14:52:28+02:00"
}
```

**Comment by diafour** [comment]
Thank you, it seems we need to check that example.

**Comment by diafour** [comment]
@Demon-DK maybe you need to freshen shell-operator image?

`docker pull flant/shell-operator:latest` and then `docker build ...` should do the job!

**Comment by Demon-DK** [comment]
Hi @diafour 

Yes, confirm, the issue has gone with the '**latest**' tagged image. Thanks.

**P.S.:** _Would be great if your team will add in the build pipeline also tagging the 'latest' image with a precisely version tag, I guess in this case it is 'flant/shell-operator:v1.0.0-beta.9'_

**Comment by diafour** [comment]
Yep! It is time for beta.9. I will test grouping imrovements in #158 with addon-operator and make a new release tomorrow.
