### ISSUE TITLE
support for hpa

### ISSUE THREAD

**Issue by anoopwebs** [flant/shell-operator#17]
It would be awesome to add hpa to the kind list https://github.com/flant/shell-operator/blob/45c6bbbfb92d5ce4675df2c07f35348fd4742138/pkg/kube_events_manager/kube_events_manager.go#L165

**Comment by diafour** [comment]
New release is available: v1.0.0-beta.2. Also, latest tag is updated. Also, changes are propogated to addon-operator.

Thank you for your time.
