### ISSUE TITLE
Add building instructions to docs to guide outside cluster debugging

### ISSUE THREAD

**Issue by rspurgeon** [flant/shell-operator#193]
Really enjoying this project, fitting a use case of mine well 👍 .  I'm trying to create a more efficient debugging cycle for my script.

The RUNNING.md instructions look like what I want for debugging outside the cluster:
https://github.com/flant/shell-operator/blob/master/RUNNING.md

However, I don't know how to build the shell-operator binary.  That seems encoded inside the GH Actions workflows, but users might want to build or pull down a release to run.  Am I missing the instructions for obtaining the released binary or a Makefile to build locally?

**Comment by diafour** [comment]
Hello! There is no Makefile and no releases of standalone binaries. We use commands in Dockerfiles and make releases as docker images. For now, you can:
1. Extract a binary from a Docker image if you run Linux.
2. Try to run a shell-operator locally in a container with a mounted ~/.kube folder.
3. For macOS you can build binary with these commands:
```
brew install jq golang
go mod download
CGO_ENABLED=1 go build ./cmd/shell-operator
```
(`brew install jq` installs libjq files system wide and CGO_*FLAGS are not needed)

No recommendations for Windows at the moment.

**Comment by rspurgeon** [comment]
@diafour thank you.  I was able to get it to build on my mac after getting the proper `go` env setup (using `goenv`), then I followed the build command inside the Dockerfile. 

Once I got it built locally, my dev -> debug cycle is *much* faster... thanks for the reply!  IMO Feel free to leave open or archive this issue.

**Comment by zuzzas** [comment]
@rspurgeon 
We'll soon have [a talk](https://kccnceu20.sched.com/event/cfea816a0ae640df39193f45baf18cc1) about this project. We'll certainly do some user-facing improvements before this date. Thanks for reporting a usability issue!

**Comment by rspurgeon** [comment]
@zuzzas & @diafour if I see other things worthy of comment, should I open issues or is there another way you're collecting feedback?

**Comment by zuzzas** [comment]
If you've got a concrete feature request then open an issue. If you've got a general question, you can reach us on Slack or Telegram. They are
