### ISSUE TITLE
Namespace wildcard matcher

### ISSUE THREAD

**Issue by diafour** [flant/shell-operator#20]
Namespace can be specified only as exact names or as any. There is a case when you want to monitor pod in namespaces like 'app-name-preview-*'. This can be done now with `"kind":"pod", "namespaceSelector": {"any": true}` and filtering events in hooks, but this is not declarative. So shell-operator filtering can be improved to run hooks only for events in namespaces that matched a regexp or at least a simple wildcard.

**Comment by distol** [comment]
Closed in favor of # 32, which proposes a much more common and much more Kubernetes-compatible way of solving the same problem.
