### ISSUE TITLE
Documented jq version = 1.6, actually used in the Shell-Operator image is 1.5

### ISSUE THREAD

**Issue by Blokje5** [flant/shell-operator#206]
The documentation refers to 1.6 as the version used for `jq`: https://github.com/flant/shell-operator/blob/master/HOOKS.md#jqfilter. However, running `jq --version` shows that the latest image is still on 1.5.

```
> jq --version
jq-1.5-1-a5b5cbe
```

Preferably the Docker Image uses `jq` version 1.6.

**Comment by diafour** [comment]
Hello!

I think you are talking about ubuntu based image? Ubuntu 18.04 still has jq-1.5 in the repository. You can use alpine based image if you need jq-1.6.

Please, consider that jq-1.6 has poor performance. It is not significant for one-time scripts, but hooks can be executed frequently and shell-operator Pod will eat up a lot of cpu. We've faced this problem with addon-operator and found a later commit that fixes the performance issue. See https://github.com/flant/libjq-go/issues/10 and issues in https://github.com/stedolan/jq repository.

It seems that documentation is outdated: shell-operator do not use jq 1.6, it uses a more recent commit, I'll fix it. 

Also, can you elaborate more on what new features of jq-1.6 do you need in hooks?

**Comment by Blokje5** [comment]
Thanks for the reply! Good to know about the performance problems in 1.6. The main reason I was using 1.6 is because of the `walk` function. But if I want that behaviour I can just add the walk function as a custom function.
