### ISSUE TITLE
How to deploy a highly available shell-operator ?

### ISSUE THREAD

**Issue by AEGQ** [flant/shell-operator#245]
Can I deploy more than one replicas of a shell-operator to provide high availability，or Is there any relevant logic in the code to ensure that only one is working through leader election  ?

## Big Thanks :)

**Comment by diafour** [comment]
Hello! There is no leader election logic right now. Can you describe your use case that needs HA?

**Comment by AEGQ** [comment]
https://github.com/LINBIT/k8s-await-election

Thanks for your reply, this project is enough for me :)
