### ISSUE TITLE
Error was: apiVersion 'v1' has no supported resources in cluster?

### ISSUE THREAD

**Issue by yzlyzlyzl** [flant/shell-operator#246]
I follow the ReadMe,run the example "101-monitor-pods", It failed。
**kubectl  logs -f monitor-pods -n example-monitor-pods** msg :
“ Cannot get GroupVersionResource info for apiVersion 'v1' kind 'Namespace' from api-server. Possibly CRD is not created before informers are started. Error was: apiVersion 'v1' has no supported resources in cluster”

![image](https://user-images.githubusercontent.com/19515744/105953371-0b97b600-60ae-11eb-9032-3ac96feef52b.png)

What's the reason？my env:
![image](https://user-images.githubusercontent.com/19515744/105953625-6fba7a00-60ae-11eb-8c5d-8fcb2e1c6333.png)

**Comment by yzlyzlyzl** [comment]
[root@master0 101-monitor-pods]# **kubectl version**
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:33:59Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
[root@master0 101-monitor-pods]# 
[root@master0 101-monitor-pods]# **lsb_release -a**
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.4.1708 (Core) 
Release:        7.4.1708
Codename:       Core
[root@master0 101-monitor-pods]# 
[root@master0 101-monitor-pods]# **kubectl  get node**
NAME      STATUS   ROLES    AGE     VERSION
master0   Ready    master   5d20h   v1.18.4
worke0    Ready    <none>   5d20h   v1.18.4

**Comment by diafour** [comment]
The root cause is `dial tcp 10.96.0.1:443: i/o timeout`. The shell-operator in Pod cannot connect to the API server. Which Kubernetes flavour do you use? Minikube/kind/kotakoda/gke/... etc. ?

**Comment by yzlyzlyzl** [comment]
> The root cause is `dial tcp 10.96.0.1:443: i/o timeout`. The shell-operator in Pod cannot connect to the API server. Which Kubernetes flavour do you use? Minikube/kind/kotakoda/gke/... etc. ?

kube1.18.4.tar.gz，No tools used，native installation。

**Comment by diafour** [comment]
Please, check the CNI in your cluster. To make sure that the API server is reachable from the shell-operator's Pod, you can use these commands:

```
$  kubectl -n example-monitor-pods exec -ti shell-operator -- bash
bash-5.0# kubectl get --raw '/version'
{
  "major": "1",
  "minor": "19",
  "gitVersion": "v1.19.4",
  "gitCommit": "d360454c9bcd1634cf4cc52d1867af5491dc9c5f",
  "gitTreeState": "clean",
  "buildDate": "2020-11-18T09:04:15Z",
  "goVersion": "go1.15.2",
  "compiler": "gc",
  "platform": "linux/amd64"
}bash-5.0#

**Comment by yzlyzlyzl** [comment]
> Please, check the CNI in your cluster. To make sure that the API server is reachable from the shell-operator's Pod, you can use these commands:
> 
> ```
> $  kubectl -n example-monitor-pods exec -ti shell-operator -- bash
> bash-5.0# kubectl get --raw '/version'
> {
>   "major": "1",
>   "minor": "19",
>   "gitVersion": "v1.19.4",
>   "gitCommit": "d360454c9bcd1634cf4cc52d1867af5491dc9c5f",
>   "gitTreeState": "clean",
>   "buildDate": "2020-11-18T09:04:15Z",
>   "goVersion": "go1.15.2",
>   "compiler": "gc",
>   "platform": "linux/amd64"
> }bash-5.0#
> ```
my env:
**bash-5.0# kubectl get --raw '/version'
Unable to connect to the server: dial tcp 10.96.0.1:443: i/o timeout
bash-5.0#** 

what reason? How solution?
Is the v1.18.4 version too low? Change to v1.19.4?

**Comment by diafour** [comment]
It is not a problem with the shell-operator. The problem is with cluster setup, something wrong with the CNI layer in your cluster. Sorry, I can't help with this, remote CNI troubleshooting in the unknown cluster is not in my skill list ;)

**Comment by yzlyzlyzl** [comment]
Ok, I will try to build the env again, thank you very much!
