### ISSUE TITLE
Can I use shell-operator to create a crud as operator-sdk does?

### ISSUE THREAD

**Issue by Kiddinglife** [flant/shell-operator#25]
Hi folks,

I went through the document that says shell-operator can be reactive to any events from any api resources. For me, shell-operato looks like a generic event listener of k8s cluster.

My question is:
for example, I can use openshift's operator-sdk to create a mysql-operator with go language.
Can I use shell-operator to do the same thing ?

thanks.

**Comment by diafour** [comment]
Sorry, don't fully understand what exactly you want to do.

**I want to create an operator for a particular software with golang and use shell-operator as a library.**
Shell-operator is not a replacement for operator-sdk, but it can be used as a library: see [addon-operator](https://github.com/flant/addon-operator).

> generic event listener of k8s cluster

shell-operator also has:
- a handful kube client (use in-cluster context or choose out-of-cluster context)
- metrics storage — a simple interface to register Prometheus metrics and avoid double registration
- schedule events
- tasks queue implementation to run ordered tasks


**I have a script with kubectl calls that retrieve information from cluster, transform it somehow and then modifies cluster's state, for example, create or update mysql deployments.**
It is the case of using shell-operator as binary. Shell-operator will call your script on kubernetes events and on schedule.

**Comment by distol** [comment]
Hi, @Kiddinglife !

Yes, you can easily use shell-operator to implement crud-like behavior. The very rough plan for that would be:
1. Define some CRD and create onStartup hook which will install it in kubernetes.
2. Create hook (or hooks) that will listen for add, update and delete events for that CRD. For example, if you trying to implement some simple MySQL operator this hooks will create (change, and delete) StatefulSet for each instance of CRD. 
3. (optional) Create crontab hooks, that will do periodical reconcilation.

But you should know, that the main purpose of shell-operator is much simpler things than a full-featured operator.

Hope I've answered your question.

**Comment by Kiddinglife** [comment]
thanks guys. I am closing this ticket.
