### ISSUE TITLE
No visible metrics when apiserver connection fails

### ISSUE THREAD

**Issue by zuzzas** [flant/shell-operator#30]
There is not indication in metrics generated by shell-operator, when connection to kube-apiserver is unstable or not working at all.

The log is full of such messages:
```E0705 10:45:58.761826       1 reflector.go:125] github.com/flant/shell-operator/pkg/kube_events_manager/kube_events_manager.go:354: Failed to list *unstructured.Unstructured: Get https://192.168.0.1:443/api/v1/namespaces/kube-system/endpoints?fieldSelector=metadata.name%3Dkube-dns&limit=500&resourceVersion=0: dial tcp 192.168.0.1:443: i/o timeout```

Unfortunately, those are not as useful as a proper Prometheus metric.

**Comment by diafour** [comment]
- klog messages are wrapped in json
- There is a new metric `shell_operator_kubernetes_client_request_result_total`. If connection is lost, it has label `code="<error>"`. See #180.
