### ISSUE TITLE
how to get the value of jq.filter'key

### ISSUE THREAD

**Issue by kingsqv** [flant/shell-operator#31]
hi 
example : "jqFilter":".metadata.labels"
how could i get the value of .metadata.labels

thanks

**Comment by diafour** [comment]
Hello! There might be a delay between invocations of  jq filter and hook, so the best way to get `.metadata.labels` in hooks is to use a `kubectl get | jq`.

**Comment by diafour** [comment]
@kingsqv  JFYI: There is a `filterResult` field in binding context for configVersion:"v1" configurations that was introduced by PR #49. Documentation: https://github.com/flant/shell-operator/blob/master/HOOKS.md#binding-context (Available as flant/shell-operator:latest)
