### ISSUE TITLE
Deduplicate informers for bindings

### ISSUE THREAD

**Issue by diafour** [flant/shell-operator#316]
**Is your feature request related to a problem? Please describe.**

Big setups such as Deckhouse have hooks with similar bindings. These bindings lead to multiple Informers with the same config.

**Describe the solution you'd like to see**

We can use one Informer for similar binding configurations and create multiple tasks from one event as implemented for Schedule events.

**Describe alternatives you've considered**

**Additional context**

**Comment by shvgn** [comment]
How can we measure the impact of the problem?

**Comment by diafour** [comment]
There is no counter for Informers right now. We can use `shell_operator_kube_snapshot_objects` and `shell_operator_kubernetes_client_request_result_total` metrics to see if deduplication will change something.
