### ISSUE TITLE
Replace objectName with nameSelector.matchNames

### ISSUE THREAD

**Issue by distol** [flant/shell-operator#33]
Reasons:
1. We already have `matchNames` in `namespaceSelector`
2. `matchNames` will allow matching for more than one object at a time

To my eye, `objectName` looks extremely ugly and non-Kubernetes-API-common, so we better use `matchNames` from prometheus-operator – at least we will be not the only ones using this keyword. And at least we will use the same approach both for namespace matching and for the object matching.

**Comment by diafour** [comment]
1. The selector field is `nameSelector.matchNames` as of #37 
1. Document this feature in HOOKS.md
