### ISSUE TITLE
fatal error: concurrent map

### ISSUE THREAD

**Issue by alrzbv** [flant/shell-operator#386]
**Expected behavior (what you expected to happen)**:
shell-operator work

**Actual behavior (what actually happened)**:
shell-operator crash

**Steps to reproduce**:
1. Run a hook with a large number of 'schedule' binding at the same time and same includeSnapshotsFrom in different queues (attaching example hook, and log)
2. Wait for a while

**Environment**:
- Shell-operator version: 1.0.7
- Kubernetes version: v1.20.5
- Installation type (kubectl apply, helm chart, etc.): kubectl apply

**Logs**:
[crash_log.txt](https://github.com/flant/shell-operator/files/8530915/crash_log.txt) | [crash_start.txt](https://github.com/flant/shell-operator/files/8531192/crash_start.txt)

**Hook example**:
[hook.txt](https://github.com/flant/shell-operator/files/8530919/hook.txt)

**Comment by diafour** [comment]
Thanks for the report. I think we'll fix it in the next release.
