### ISSUE TITLE
configmap update cannot be monitored

### ISSUE THREAD

**Issue by pixiake** [flant/shell-operator#43]
my hook：
{
	"onKubernetesEvent": [{
		"name": "Monitor configmap",
		"kind": "ConfigMap",
		"event": ["add", "update"],
		"objectName": "test-config",
		"namespaceSelector": {
			"any": true
		},
		"jqFilter": ".metadata.labels",
		"allowFailure": false
	}]
}

It was monitored when I created the configmap ，but not when I modified the configmap
Is there anything wrong with my hook？

**Comment by zuzzas** [comment]
>`"jqFilter": ".metadata.labels"`

You've modified the labels, right?

**Comment by pixiake** [comment]
@zuzzas Sorry, I didn't notice "jqFilter".   After modifying the` jqFilter` to` .data`, everything works fine. Thanks!
