### ISSUE TITLE
monitor-pods example stopped working after merging #52

### ISSUE THREAD

**Issue by jacobsin** [flant/shell-operator#54]
flant/shell-operator:latest failed to start up with monitor-pods example hook over the weekend

```
2019-09-30T09:25:35Z ERROR : MAIN Fatal: initialize hook manager: creating hook 'pods-hooks.sh': load hook 'pods-hooks.sh' config: 2 errors occurred:
 * kubernetes.watchEvent must be of type string: "array"
 * kubernetes.watchEvent should be one of [Added Modified Deleted]
hook --config output: {
  "configVersion":"v1",
  "kubernetes":[{
    "apiVersion": "v1",
    "kind": "Pod",
    "watchEvent":["Added"]
  }]
}
```

Reverting to flant/shell-operator:v1.0.0-beta.5 (3 month ago) works again for the same hooks

**Comment by jacobsin** [comment]
But reverting to the previous tag means losing the latest non-blocking executor and synchronization event :(

**Comment by jacobsin** [comment]
Looks like instead of array it's now expecting a single string instead of an array

https://github.com/flant/shell-operator/blob/85cf1a6e98d23178c83493254b9af7257dfddf56/pkg/hook/config/schemas.go#L112

Is the change of schema intentional - if yes, examples like  https://github.com/flant/shell-operator/blob/85cf1a6e98d23178c83493254b9af7257dfddf56/examples/101-monitor-pods/hooks/pods-hook.sh#L10 just need to be updated

**Comment by diafour** [comment]
Thank you! The reason is bad schema. PR #55 is ready.

**Comment by diafour** [comment]
`monitor pods` example is working with `latest` image.
