### ISSUE TITLE
build Dockerfile  failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed

### ISSUE THREAD

**Issue by Forest-L** [flant/shell-operator#64]
=> ERROR [stage-0 6/6] RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w -X 'github.com/flant/shell-operator/pk  77.4s
------                                                                                                                      
 > [stage-0 6/6] RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w -X 'github.com/flant/shell-operator/pkg/app.Version=latest'" -o shell-operator ./cmd/shell-operator:                                                                             
#13 24.74 # k8s.io/utils/trace                                                                                              
#13 24.74 /go/src/k8s.io/utils/trace/trace.go:100:57: invalid operation: stepThreshold == 0 || stepDuration > stepThreshold || klog.V(4) (mismatched types bool and klog.Verbose)                                                                       
#13 24.74 /go/src/k8s.io/utils/trace/trace.go:112:56: invalid operation: stepThreshold == 0 || stepDuration > stepThreshold || klog.V(4) (mismatched types bool and klog.Verbose)
#13 37.42 # k8s.io/client-go/transport
#13 37.42 /go/src/k8s.io/client-go/transport/round_trippers.go:70:11: cannot convert klog.V(9) (type klog.Verbose) to type bool
#13 37.42 /go/src/k8s.io/client-go/transport/round_trippers.go:72:11: cannot convert klog.V(8) (type klog.Verbose) to type bool
#13 37.42 /go/src/k8s.io/client-go/transport/round_trippers.go:74:11: cannot convert klog.V(7) (type klog.Verbose) to type bool
#13 37.42 /go/src/k8s.io/client-go/transport/round_trippers.go:76:11: cannot convert klog.V(6) (type klog.Verbose) to type bool
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w -X 'github.com/flant/shell-operator/pkg/app.Version=$appVersion'" -o shell-operator ./cmd/shell-operator]: buildkit-runc did not terminate sucessfully

**Comment by diafour** [comment]
It seems that you don't use `docker build`. What command do you run to build image and what Dockerfile?

**Comment by Forest-L** [comment]
docker buildx build . beta5 branch has error.

**Comment by diafour** [comment]
Ouch. beta.5 has `go get` in Dockerfile. There was a fix for this: #39.

beta.6 is not ready yet, but you can use master, it is working with old hook configuration format.
