### ISSUE TITLE
Gradual Increase in Memory Consumption

### ISSUE THREAD

**Issue by J0ram** [flant/shell-operator#653]
Hi,

Since 1.4.8 we have observed our shell-operator pods slowly consuming memory over time:
![image](https://github.com/user-attachments/assets/5addacb4-9e06-4768-a6fc-76f9386be1db)

I made a local branch with pprof installed and it appears to be logrus that is not releasing its memory:
![image](https://github.com/user-attachments/assets/acb9846c-9cac-4a64-b00d-66bcf02ffae7)

**Environment**:
- 1.48 - 1.4.11 (we've tested each version on release)
- Kubernetes version: AKS 1.29.4
- Installation type Helm

Worth noting that 1.4.7 behaves as expected on the same cluster.

**Anything else we should know?**:
I find it odd that nobody else is reporting this issue - I can only assume it's some oddity in our environment but I'm pretty much out of ideas.

From what I can see the version of the logrus package hasn't changed between versions of this application (particularly 1.47 - 1.48). If you have any ideas of how we could debug further that would be appreciated.

I've attached the heap dump if that's of any help

Thanks

[heap.zip](https://github.com/user-attachments/files/16959990/heap.zip)

**Comment by sidineyc** [comment]
Also hitting this.

Shell Operator: 1.4.10
K8s: 1.29.8

**Comment by kyale** [comment]
Same here with multiple operators running on different clusters. Pod crashes and restarts when it hits memory limit.
<img width="1533" alt="Screenshot 2024-10-18 at 14 51 25" src="https://github.com/user-attachments/assets/87961018-fef2-4f52-83f4-ead253bdaff8">

**Comment by vladimirfx** [comment]
Checked 1.4.14 - classic memory leak:

<img width="2219" alt="Снимок экрана 2024-10-20 в 16 38 52" src="https://github.com/user-attachments/assets/40d3f334-1322-4ff3-8500-41124af3de84">

Because of Go 1.22 and `GOLIMIT`, the operator uses a lot of CPU on GC before being killed by Kubelet.

**Comment by yalosev** [comment]
Hello. Thank you for the report. We also met the logrus leak a few time ago. we're currently working on [changing the logger](https://github.com/flant/shell-operator/pull/671).

**Comment by yalosev** [comment]
We have a quick fix in [v1.4.15](https://github.com/flant/shell-operator/releases/tag/v1.4.15). Could you try it, please.

**Comment by vladimirfx** [comment]
> We have a quick fix in [v1.4.15](https://github.com/flant/shell-operator/releases/tag/v1.4.15). Could you try it, please.

The memory profile looks better but I hit by log duplication https://github.com/flant/shell-operator/issues/675

Keeps monitoring.

**Comment by J0ram** [comment]
We've been running 1.4.15 overnight - memory usage is completely flat :)

Thanks all
