### ISSUE TITLE
Duplicate log lines with hook output on v1.4.15

### ISSUE THREAD

**Issue by vladimirfx** [flant/shell-operator#675]
**Expected behavior (what you expected to happen)**:

Each hook stdout/stderr output should be logged once.

**Actual behavior (what actually happened)**:

There are many full and partial duplicates on hook output in logs.

**Steps to reproduce**:
1. Print something (maybe multiline or stderr) from a hook script
2. See pod logs

**Environment**:
- Shell-operator version: 1.4.15
- Kubernetes version: 1.30.5
- Installation type (kubectl apply, helm chart, etc.): Flux

**Anything else we should know?**:

[controller.log](https://github.com/user-attachments/files/17494851/controller.log)

**Additional information for debugging (if necessary)**:

https://github.com/cit-consulting/hetzner-failoverip-controller/blob/v0.8/docker/hooks/sync-fip.sh

**Comment by miklezzzz** [comment]
Hello, could you please try adding `-s` flag to the curl calls in your [script](https://github.com/cit-consulting/hetzner-failoverip-controller/blob/5835f2651b6f1384f982e4197a40a1cdac82024f/docker/hooks/lib/process-resource.sh#L45) and give it a try?

**Comment by vladimirfx** [comment]
Do so already: 
[controller.log](https://github.com/user-attachments/files/17506673/controller.log)

**Comment by miklezzzz** [comment]
Fixed in the linked PR.
Thanks for the report!
