### ISSUE TITLE
watchEvent - Deleted

### ISSUE THREAD

**Issue by D1abloRUS** [flant/shell-operator#73]
If you use only watchEvent - Deleted and kind deployment, then delete events are ignored, if add Added, then everything is ok

**Comment by diafour** [comment]
Did some tests, Deleted is fixed by https://github.com/flant/shell-operator/pull/66. I hope we merge a pile of PRs soon and a fix will become available in the latest image.

**Comment by diafour** [comment]
:tada: `latest` is updated.
