### ISSUE TITLE
Add documentation of environment variables

### ISSUE THREAD

**Issue by diafour** [flant/shell-operator#84]
There is no description of SHELL_OPERATOR_* and LOG_* envs.

**Comment by florianrusch** [comment]
Are there any other environment variables besides those listed here: https://github.com/flant/shell-operator/blob/master/pkg/app/app.go#L30-L71

**Comment by diafour** [comment]
There is only one hidden variable for now: https://github.com/flant/shell-operator/blob/a45359be867bca94e4971621b3f0ae2867205835/pkg/kube_events_manager/util.go#L26

`JQ_EXEC=yes` to use jq as executable — it is more for developing purposes.
