### ISSUE TITLE
Latest version of shell-operator

### ISSUE THREAD

**Issue by kofan** [flant/shell-operator#97]
Hi! This is rather a question than an issue.

The current documentation that describes `v1` API (with `Synchronization`type of hook binding context and other features) is inconsistent with the latest official release of the shell-operator which is `v1.0.0-beta.5`. Initially, our team implemented the solution using the shell-operator API described in the docs, but then we figured out it did not work if we used `v1.0.0-beta.5` release. That's why we had to use `:latest` tag of the shell-operator image to make it work... 
I'm wondering why there were no releases for more than 6 months already? Are you planning to release either `v1.0.0-beta.6` or `v1.0.0` version soon?

And thank you for everything you are doing - shell-operator is an awesome tool!

**Comment by diafour** [comment]
Hello! shell-operator is a base for addon-operator and now we are in a process of huge rethinking of addon-operator features, so shell-operator was hugely refactored. I've created a combined PR with last changes and release a v1.0.0-beta.6 version — it will be available soon on hub.docker.com.

For now, it is lack of documentation and some tests are broken. The plan is to finish adding features for addon-operator, then update documentation and continue to improve testing (https://github.com/flant/shell-operator/issues/63).

**Comment by kofan** [comment]
Thank you a lot!
